InterpolSystem.Web/Areas/BountyAdmin/Models/MissingPeople/MissingPeopleCreateFormViewModel.cs
namespace InterpolSystem.Web.Areas.BountyAdmin.Models.MissingPeople
{
    using Data.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using static Data.DataConstants;

    public class MissingPeopleCreateFormViewModel : LanguageAndCountryListingsViewModel, IValidatableObject
    {
        private const string InvalidDateInThePast = "01/01/1800";

        [Required]
        [MaxLength(IdentityMissingNamesMaxLength)]
        [MinLength(IdentityMissingNamesMinLength)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(IdentityMissingNamesMaxLength)]
        [MinLength(IdentityMissingNamesMinLength)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [MaxLength(IdentityMissingNamesMaxLength)]
        [Display(Name = "All names")]
        public string AllNames { get; set; }

        public Gender Gender { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of birth")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [MaxLength(IdentityMissingPlaceOfBirthMaxLength)]
        [MinLength(IdentityMissingPlaceOfBirthMinLength)]
        [Display(Name = "Place of birth")]
        public string PlaceOfBirth { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of disappearance")]
        public DateTime DateOfDisappearance { get; set; }

        [Required]
        [MaxLength(IdentityMissingPlaceOfDisappearanceMaxLength)]
        [MinLength(IdentityMissingPlaceOfDisappearanceMinLength)]
        [Display(Name = "Place of disappearance")]
        public string PlaceOfDisappearance { get; set; }

        [Range(0, double.MaxValue)]
        [Display(Name = "Height (in meters)")]
        public double Height { get; set; }

        [Range(0, double.MaxValue)]
        [Display(Name = "Weight (in kg)")]
        public double Weight { get; set; }

        [Display(Name = "Color of hair")]
        public Color HairColor { get; set; }

        [Display(Name = "Color of eyes")]
        public Color EyeColor { get; set; }

        [Required]
        [MaxLength(PhysicalDescriptionPcitureMaxLength)]
        [MinLength(PhysicalDescriptionPcitureMinLength)]
        [RegularExpression(@"^(http|https):\/\/.*$", ErrorMessage = "The url must start with http/https://")]
        [Display(Name = "Picture URL")]
        public string PictureUrl { get; set; }

        [MaxLength(PhysicalDescriptionScarsOrMarksMaxLength)]
        [Display(Name = "Scars or any other distinguishing marks")]
        public string ScarsOrDistinguishingMarks { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.DateOfBirth <= DateTime.Parse(InvalidDateInThePast))
            {
                yield return new ValidationResult("Date of birth should be after 1800.");
            }

            if (this.DateOfDisappearance <= DateTime.Parse(InvalidDateInThePast))
            {
                yield return new ValidationResult("Date of disappearance should be after 1800.");
            }
        }
    }
}

InterpolSystem.Web/Areas/BountyAdmin/Models/MissingPeople/MissingPeopleFormViewModel.cs
namespace InterpolSystem.Web.Areas.BountyAdmin.Models.MissingPeople
{
    using Data.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using static Data.DataConstants;

    public class MissingPeopleFormViewModel : LanguageAndCountryListingsViewModel, IValidatableObject
    {
        [Required]
        [MaxLength(IdentityMissingNamesMaxLength)]
        [MinLength(IdentityMissingNamesMinLength)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(IdentityMissingNamesMaxLength)]
        [MinLength(IdentityMissingNamesMinLength)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [MaxLength(IdentityMissingNamesMaxLength)]
        [Display(Name = "All names")]
        public string AllNames { get; set; }

        public Gender Gender { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = DateFormatString)]
        [Display(Name = "Date of birth")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [MaxLength(IdentityMissingPlaceOfBirthMaxLength)]
        [MinLength(IdentityMissingPlaceOfBirthMinLength)]
        [DisplayFormat(DataFormatString = DateFormatString)]
        [Display(Name = "Place of birth")]
        public string PlaceOfBirth { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of disappearance")]
        public DateTime DateOfDisappearance { get; set; }

        [Required]
        [MaxLength(IdentityMissingPlaceOfDisappearanceMaxLength)]
        [MinLength(IdentityMissingPlaceOfDisappearanceMinLength)]
        [Display(Name = "Place of disappearance")]
        public string PlaceOfDisappearance { get; set; }

        [Range(0, double.MaxValue)]
        [Display(Name = "Height (in meters)")]
        public double Height { get; set; }

        [Range(0, double.MaxValue)]
        [Display(Name = "Weight (in kg)")]
        public double Weight { get; set; }

        [Display(Name = "Color of hair")]
        public Color HairColor { get; set; }

        [Display(Name = "Color of eyes")]
        public Color EyeColor { get; set; }

        [Required]
        [MaxLength(PhysicalDescriptionPcitureMaxLength)]
        [MinLength(PhysicalDescriptionPcitureMinLength)]
        [RegularExpression(@"^(http|https):\/\/.*$", ErrorMessage = "The url must start with http/https://")]
        [Display(Name = "Picture URL")]
        public string PictureUrl { get; set; }

        [MaxLength(PhysicalDescriptionScarsOrMarksMaxLength)]
        [Display(Name = "Scars or any other distinguishing marks")]
        public string ScarsOrDistinguishingMarks { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.DateOfBirth <= DateTime.Parse(InvalidDateInThePast))
            {
                yield return new ValidationResult("Date of birth should be after 1800.");
            }

            if (this.DateOfDisappearance <= DateTime.Parse(InvalidDateInThePast))
            {
                yield return new ValidationResult("Date of disappearance should be after 1800.");
            }
        }
    }
}

InterpolSystem.Web/Models/MissingPeople/MissingPeoplePageListingModel.cs
namespace InterpolSystem.Web.Models.MissingPeople
{
    using InterpolSystem.Services.Blog.Models;
    using Services.Models.MissingPeople;
    using Shared;
    using System.Collections.Generic;

    public class MissingPeoplePageListingModel : SearchFormViewModel
    {
        public IEnumerable<MissingPeopleListingServiceModel> MissingPeople { get; set; } = new List<MissingPeopleListingServiceModel>();

        public int TotalPages { get; set; }

        public int CurrentPage { get; set; }

        public int PreviousPage => this.CurrentPage == 1 ? 1 : this.CurrentPage - 1;

        public int NextPage => this.CurrentPage == this.TotalPages ? this.TotalPages : this.CurrentPage + 1;

        public IEnumerable<ArticlesListingsServiceModel> Articles { get; set; }

    }
}

InterpolSystem.Web/Models/MissingPeople/SearchFormViewModel.cs
namespace InterpolSystem.Web.Models.MissingPeople
{
    using Data.Models.Enums;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class SearchFormViewModel
    {
        public string SearchByFirstName { get; set; }

        public string SearchByLastName { get; set; }

        public string SearchByDistinguishMarks { get; set; }

        public int? SearchByAge { get; set; }
        
        [Display(Name = "Search by Gender")]
        public bool EnableGenderSearch { get; set; }

        public Gender SelectedGender { get; set; }

        [Display(Name = "Search by Country")]
        public bool EnableCountrySearch { get; set; }

        public IEnumerable<SelectListItem> Countries { get; set; }

        public int? SelectedCountryId { get; set; }

        public int SearchCriteriaTotalPages { get; set; }
    }
}

InterpolSystem.Web/Areas/Blog/Controllers/ArticlesController.cs
namespace InterpolSystem.Web.Areas.Blog.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Articles;
    using Services.Blog;
    using Services.Html;
    using System;

    using static WebConstants;

    [Area(BlogArea)]
    [Authorize(Roles = BloggerRole)]
    public class ArticlesController : Controller
    {
        private readonly IArticleService articleService;
        private readonly UserManager<User> userManager;
        private readonly IHtmlService htmlService;

        public ArticlesController(
            IArticleService articleService,
            UserManager<User> userManager,
            IHtmlService htmlService)
            
        {
            this.articleService = articleService;
            this.userManager = userManager;
            this.htmlService = htmlService;
        }

        [AllowAnonymous]
        public IActionResult Index()
            => View(this.articleService.All());

        [AllowAnonymous]
        public IActionResult Details(int id)
           => this.ViewOrNotFound(this.articleService.ById(id));

        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(PublishArticleFormViewModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (userId == null)
            {
                TempData.AddErrorMessage("The author does not exist.");
                return View();
            }

            var sanitizedContent = this.htmlService.Sanitize(model.Content);

            try
            {
                this.articleService.Create(model.Title, sanitizedContent, userId);
            }
            catch (InvalidOperationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            TempData.AddSuccessMessage("Successfully published.");

            return RedirectToAction(nameof(Index));
        }
    }
}

InterpolSystem.Web/Areas/BountyAdmin/Controllers/MissingPeopleController.cs
namespace InterpolSystem.Web.Areas.BountyAdmin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Models.MissingPeople;
    using Services.BountyAdmin;
    using System.Collections.Generic;
    using System.Linq;
    using Web.Infrastructure.Extensions;

    public class MissingPeopleController : BaseBountyAdminController
    {
        private readonly IBountyAdminService bountyAdminService;

        public MissingPeopleController(IBountyAdminService bountyAdminService)
        {
            this.bountyAdminService = bountyAdminService;
        }

        public IActionResult Index()
        {
            // TO DO
            return View();
        }

        public IActionResult Create()
         => View(new MissingPeopleCreateFormViewModel
         {
             Languages = this.GetLanguages(),
             Countries = this.GetCountries()
         });

        [HttpPost]
        public IActionResult Create(MissingPeopleCreateFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Languages = this.GetLanguages();
                model.Countries = this.GetCountries();

                return View(model);
            }

            var existingLanguages = this.bountyAdminService.IsLanguagesExisting(model.SelectedLanguages);
            var existingCountries = this.bountyAdminService.IsCountriesExisting(model.SelectedCountries);

            if (!existingLanguages || !existingCountries)
            {
                return new BadRequestObjectResult("Unexisting language or country.");
            }

            this.bountyAdminService.Create(
                model.FirstName,
                null,
                model.Gender,
                model.DateOfBirth,
                model.PlaceOfBirth,
                model.DateOfDisappearance,
                model.PlaceOfDisappearance,
                model.Height,
                model.Weight,
                model.HairColor,
                model.EyeColor,
                model.PictureUrl,
                model.SelectedCountries,
                model.SelectedLanguages,
                model.AllNames,
                model.ScarsOrDistinguishingMarks);

            TempData.AddSuccessMessage("Person successfully added to the system.");

            return RedirectToAction(nameof(Index));
        }

        private List<SelectListItem> GetLanguages()
            => this.bountyAdminService.GetLanguagesList()
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id.ToString()
                })
                .ToList();

        private List<SelectListItem> GetCountries()
            => this.bountyAdminService.GetCountriesList()
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id.ToString()
                })
                .ToList();
    }
}

InterpolSystem.Web/Controllers/MissingPeopleController.cs
namespace InterpolSystem.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Models.MissingPeople;
    using Models.Shared;
    using Services;
    using Services.Blog;
    using Services.BountyAdmin;
    using System;

    using static WebConstants;

    public class MissingPeopleController : BasePeopleController
    {
        private readonly IArticleService articleService;
        private readonly IMissingPeopleService peopleService;

        public MissingPeopleController(
            IArticleService articleService,
            IMissingPeopleService peopleService,
            IBountyAdminService bountyAdminService)
            : base(bountyAdminService)
        {
            this.peopleService = peopleService;
            this.articleService = articleService;
        }

        public IActionResult Index(int page = 1)
            => View(new MissingPeoplePageListingModel
            {
                MissingPeople = this.peopleService.All(page, PageSize),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(this.peopleService.Total() / (double)PageSize),
                Countries = this.GetCountries(),
                Articles = articleService.LastSixArticles()
            });

        public IActionResult Details(int id)
        {
            var existingPerson = this.peopleService.IsPersonExisting(id);

            if (!existingPerson)
            {
                return BadRequest();
            }

            var person = this.peopleService.GetPerson(id);

            return View(person);
        }

        public IActionResult Search(SearchFormViewModel model, int page = 1)
            => View(new MissingPeoplePageListingModel
            {
                CurrentPage = page,
                MissingPeople = this.peopleService.SearchByComponents(
                    model.EnableCountrySearch,
                    model.SelectedCountryId ?? 0,
                    model.EnableGenderSearch,
                    model.SelectedGender,
                    model.SearchByFirstName,
                    model.SearchByLastName,
                    model.SearchByDistinguishMarks,
                    model.SearchByAge ?? 0,
                    page,
                    PageSize),
                SearchCriteriaTotalPages = this.peopleService.SearchPeopleCriteriaCounter,
                TotalPages = (int)Math.Ceiling(this.peopleService.SearchPeopleCriteriaCounter / (double)PageSize),
                Articles = articleService.LastSixArticles()
            });
    }
}

InterpolSystem.Web/Views/MissingPeople/Details.cshtml
@model MissingPeopleDetailsServiceModel

@{
    ViewData["Title"] = $"{Model.FirstName} {Model.LastName}";
}

<a asp-controller="MissingPeople" asp-action="Index" class="btn btn-primary">Back to all</a>

@if (this.User.IsInRole(WebConstants.WantedMissingPeopleRole) || this.User.IsInRole(WebConstants.AdministratorRole))
{
    <a asp-area="BountyAdmin" asp-controller="MissingPeople" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-4">
        <img src="@Model.PhysicalDescription.PictureUrl" class="img-responsive center-block" alt="@Model.LastName picture" />
    </div>
    <div class="col-md-8">
        <div class="panel panel-default panel-heading">
            <p class="panel-title panel-heading text-capitalize">identity particulars</p>
            <div class="panel-body">
                <p>First name: <span class="text-custom">@Model.FirstName</span></p>
                <p>Last name: <span class="text-custom">@Model.LastName</span></p>

                @if (Model.AllNames != null)
                {
                     <p>Full name: <span class="text-custom">@Model.AllNames</span></p>
                }

                <p>Sex: <span class="text-custom">@Model.Gender.ToString()</span></p>
                <p>Date of birth: <span class="text-custom">@Model.DateOfBirth.ToShortDateString()</span></p>
                <p>Place of birth: <span class="text-custom">@Model.PlaceOfBirth</span></p>
                <p>Nationality: <span class="text-custom">@(string.Join(", ", Model.Nationalities.Select(n => n.Name)))</span></p>
            </div>
        </div>
        <div class="panel panel-default panel-heading">
            <p class="panel-title panel-heading text-capitalize">physical description</p>
            <div class="panel-body">
                <p>Color of hair: <span class="text-custom">@Model.PhysicalDescription.HairColor.ToString()</span></p>
                <p>Color of eyes: <span class="text-custom">@Model.PhysicalDescription.EyeColor.ToString()</span></p>
                <p>Height: <span class="text-custom">@Model.PhysicalDescription.Height cm</span></p>
                <p>Weight: <span class="text-custom">@Model.PhysicalDescription.Weight kg</span></p>

                @if (Model.PhysicalDescription.ScarsOrDistinguishingMarks != null)
                {
                    <p>Scars or distinguishing marks: <span class="text-custom">@Model.PhysicalDescription.ScarsOrDistinguishingMarks</span></p>
                }

                <p>Languages spoken: <span class="text-custom">@(string.Join(", ", Model.SpokenLanguages.Select(l => l.Name)))</span></p>
            </div>
        </div>
        <div class="panel panel-default panel-heading">
            <p class="panel-title panel-heading text-capitalize">date of disappearance</p>
            <div class="panel-body">
                <p>Date of disappearance: <span class="text-custom">@Model.DateOfDisappearance.ToShortDateString()</span></p>
                <p>Place of disappearance: <span class="text-custom">@Model.PlaceOfDisappearance</span></p>
            </div>
        </div>    
        <div class="panel-footer">
            <p class="text-danger text-capitalize">if you have any information please contact:</p>
            <p>Your national or local police</p>
            <p><a href="mailto:someone@example.com?Subject=FoundMissingPerson" class="text-primary" target="_top">General Secretariat of INTERPOL</a></p>
        </div>
    </div>
</div>

InterpolSystem.Web/Views/MissingPeople/Index.cshtml
@model MissingPeoplePageListingModel

@{
    ViewData["Title"] = "Missing People";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<br/>
<div class="row form-group">
    <form asp-action="Search">
        <div class="col-md-12">
            <div class="col-md-6">
                <input asp-for="SearchByFirstName" placeholder="First name..." class="form-control form-search-margin" />
                <input asp-for="SearchByLastName" placeholder="Last name..." class="form-control form-search-margin" />
                <input asp-for="SearchByDistinguishMarks" placeholder="Distinguish marks..." class="form-control form-search-margin" />
                <input asp-for="SearchByAge" min="0" max="120" step="1" placeholder="Age..." class="form-control form-search-margin" />
            </div>
            <div class="col-md-6">
                <div class="col-md-6">
                    <label asp-for="EnableGenderSearch"></label>
                    <input asp-for="EnableGenderSearch" />
                    <select asp-for="SelectedGender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control"></select>
                </div>
                <div class="col-md-6">
                    <label asp-for="EnableCountrySearch"></label>
                    <input asp-for="EnableCountrySearch" />
                    <select name="SelectedCountryId" asp-items="Model.Countries" class="form-control dropdown">
                        <option disabled selected>--- SELECT ---</option>
                    </select>
                </div>
                <div class="col-md-2 pull-right">
                    <input type="submit" name="submit" value="Search" class="btn btn-primary pull-right search-button" />
                </div>
            </div>
        </div>
    </form>
</div>
<hr class="custom-hr"/>
<div class="row col-md-12">
    @await Html.PartialAsync("_MissingPeopleListingsPartial", Model)
</div>

InterpolSystem.Web/Views/MissingPeople/Search.cshtml
@model MissingPeoplePageListingModel

@{
    ViewData["Title"] = "Search results";
}

<h2>@ViewData["Title"]</h2>

@if (Model.MissingPeople.Any())
{
    <h3>Found @Model.SearchCriteriaTotalPages matched results.</h3>

    <div class="row">
        @await Html.PartialAsync("_MissingPeopleListingsPartial", Model)
    </div>
}
else
{
    <h3>No people to show.</h3>
}

InterpolSystem.Web/Views/MissingPeople/_MissingPeopleListingsPartial.cshtml
@model MissingPeoplePageListingModel

@{
    var previousDisabled = Model.CurrentPage == 1 ? "disabled" : string.Empty;
    var nextDisabled = Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty;
}

<div class="row missing-people-listings">
    <div class="col-md-9">
        @foreach (var person in Model.MissingPeople)
        {
            <div class="col-md-4 col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">
                        <a asp-controller="MissingPeople" asp-action="Details" asp-route-id="@person.Id">Details</a>
                    </div>
                    <div class="panel-body">
                        <img src="@person.PictureUrl" class="img-responsive center-block" />
                        <br />
                        <p class="text-center">
                            @($"Name: {person.FirstName} {person.LastName}")
                        </p>
                        <p class="text-center">
                            @($"Age today: {DateTime.UtcNow.Year - person.DateOfBirth.Year} years old")
                        </p>
                        <p class="text-center">
                            @($"Nationality: {person.GivenNationalities}")
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-3  article-menu">
        <a asp-area="Blog" asp-controller="Articles" asp-action="Index">
            <p class="text-center text-uppercase text-danger">Last News:</p>
        </a>
        <div class="row custom-menu">
            @await Html.PartialAsync("~/Areas/Blog/Views/Articles/_AllArticlesPartial.cshtml", Model.Articles)
        </div>
    </div>
</div>
<ul class="pagination pagination-lg">
    <li class="@previousDisabled">
        <a asp-route-page="@Model.PreviousPage" aria-label="Previous">
            <span aria-hidden="true">«</span>
        </a>
    </li>
    @for (int i = 1; i <= Model.TotalPages; i++)
    {
        <li class="@(Model.CurrentPage == i ? "active" : string.Empty)">
            <a asp-route-page="@i">@i</a>
        </li>
    }
    <li class="@nextDisabled">
        <a asp-route-page="@Model.NextPage" aria-label="Next">
            <span aria-hidden="true">»</span>
        </a>
    </li>
</ul>