InterpolSystem.Web/Areas/Admin/Controllers/UsersController.cs
namespace InterpolSystem.Web.Areas.Admin.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Models.Users;
    using Services.Admin;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using static WebConstants;

    public class UsersController : BaseAdminController
    {
        private readonly IAdminUserService adminService;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public UsersController(
            IAdminUserService adminService, 
            RoleManager<IdentityRole> roleManager,
            UserManager<User> userManager)
        {
            this.adminService = adminService;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
            => View(new UserListingsViewModel
            {
                Users = this.adminService.All(),
                Roles = this.GetRoles()
            });

        public IActionResult Create()
            => View(new CreateUserFormViewModel
            {
                Roles = this.GetRoles()
            });

        [HttpPost]
        [LogEmployees]
        public async Task<IActionResult> Create(CreateUserFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(this.ReturnUserFormViewModelWithErrors(model));
            }

            var user = new User
            {
                UserName = model.UserName,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName
            };

            var password = this.GenerateRandomPassword();
            var result = await userManager.CreateAsync(user, password);

            if (!result.Succeeded)
            {
                TempData[TempDataErrorMessageKey] = $"User with username {model.UserName} or email {model.Email} already exists.";
                return View(this.ReturnUserFormViewModelWithErrors(model));
            }

            if (!model.WithoutRole)
            {
                var existingRole = await this.roleManager.RoleExistsAsync(model.Role);

                if (!existingRole)
                {
                    ModelState.AddModelError(string.Empty, "Invalid role.");
                }

                await this.userManager.AddToRoleAsync(user, model.Role);
            }

            TempData[TempDataSuccessMessageKey] = $"Successfully created with password: {password}";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [LogEmployees]
        public async Task<IActionResult> ChangePassword(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            var existingUser = await this.userManager.FindByIdAsync(id);

            if (existingUser == null)
            {
                return NotFound();
            }

            var isUserAdmin = await this.userManager.IsInRoleAsync(existingUser, AdministratorRole);

            if (isUserAdmin)
            {
                ModelState.AddModelError(string.Empty, "Invalid operation.");
            }

            if (!ModelState.IsValid)
            {
                this.TempData.AddErrorMessage("Cannot modify other administrator.");
                return RedirectToAction(nameof(Index));
            }

            var token = await this.userManager.GeneratePasswordResetTokenAsync(existingUser);
            var newPassword = this.GenerateRandomPassword();

            var result = await this.userManager.ResetPasswordAsync(existingUser, token, newPassword);

            if (!result.Succeeded)
            {
                return BadRequest("Failed to reset the password.");
            }

            this.TempData.AddSuccessMessage($"Successfully reset the password. The new password is: {newPassword}");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [LogEmployees]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            var existingUser = await this.userManager.FindByIdAsync(id);

            if (existingUser == null)
            {
                return NotFound();
            }

            var isUserAdmin = await this.userManager.IsInRoleAsync(existingUser, AdministratorRole);

            if (isUserAdmin)
            {
                ModelState.AddModelError(string.Empty, "Invalid operation.");
            }

            if (!ModelState.IsValid)
            {
                this.TempData.AddErrorMessage("Cannot delete administrator.");
                return RedirectToAction(nameof(Index));
            }

            await this.userManager.DeleteAsync(existingUser);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [LogEmployees]
        public async Task<IActionResult> AddToRole(AddRemoveUserToRoleViewModel model)
        {
            var existingRole = await this.roleManager.RoleExistsAsync(model.Role);
            var selectedUser = await this.userManager.FindByIdAsync(model.UserId);
            var existingUser = selectedUser != null;

            if (!existingRole || !existingUser)
            {
                ModelState.AddModelError(string.Empty, "Invalid identity details.");
            }

            if (!ModelState.IsValid)
            {
                this.TempData.AddErrorMessage("Either user or role are not valid.");
                return RedirectToAction(nameof(Index));
            }

            var result = await this.userManager.AddToRoleAsync(selectedUser, model.Role);

            if (!result.Succeeded)
            {
                this.TempData.AddErrorMessage($"{selectedUser.UserName} is already in role {model.Role}");
                return RedirectToAction(nameof(Index));
            }

            this.TempData.AddSuccessMessage($"User {selectedUser.UserName} successfully added to role {model.Role}.");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [LogEmployees]
        public async Task<IActionResult> RemoveFromRole(AddRemoveUserToRoleViewModel model)
        {
            var existingRole = await this.roleManager.RoleExistsAsync(model.Role);
            var selectedUser = await this.userManager.FindByIdAsync(model.UserId);
            var isUserInRole = await this.userManager.IsInRoleAsync(selectedUser, model.Role);
            var existingUser = selectedUser != null;

            if (!existingRole || !existingUser || !isUserInRole)
            {
                ModelState.AddModelError(string.Empty, "Invalid identity details.");
            }

            if (!ModelState.IsValid)
            {
                this.TempData.AddErrorMessage("Either user or role are not valid.");
                return RedirectToAction(nameof(Index));
            }

            var result = await this.userManager.RemoveFromRoleAsync(selectedUser, model.Role);

            if (!result.Succeeded)
            {
                this.TempData.AddErrorMessage($"{selectedUser.UserName} is not in role {model.Role}");
                return RedirectToAction(nameof(Index));
            }

            this.TempData.AddSuccessMessage($"User {selectedUser.UserName} successfully removed from role {model.Role}.");
            return RedirectToAction(nameof(Index));
        }

        private List<SelectListItem> GetRoles()
            => this.roleManager.Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
                .ToList();

        private CreateUserFormViewModel ReturnUserFormViewModelWithErrors(CreateUserFormViewModel model)
            => new CreateUserFormViewModel
            {
                Roles = this.GetRoles(),
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                UserName = model.UserName,
                WithoutRole = model.WithoutRole
            };

        private string GenerateRandomPassword(PasswordOptions opts = null)
        {
            if (opts == null)
            {
                // by default
                opts = new PasswordOptions()
                {
                    RequiredLength = 10,
                    RequiredUniqueChars = 4,
                    RequireDigit = true,
                    RequireLowercase = true,
                    RequireNonAlphanumeric = true,
                    RequireUppercase = true
                };
            }
            
            string[] randomChars = new[] 
            {
                "ABCDEFGHJKLMNOPQRSTUVWXYZ",    // uppercase 
                "abcdefghijkmnopqrstuvwxyz",    // lowercase
                "0123456789",                   // digits
                "@$"                            // non-alphanumeric
            };

            Random rand = new Random(Environment.TickCount);
            var chars = new List<char>();

            if (opts.RequireUppercase)
            {
                chars.Insert(rand.Next(0, chars.Count),
                    randomChars[0][rand.Next(0, randomChars[0].Length)]);
            }

            if (opts.RequireLowercase)
            {
                chars.Insert(rand.Next(0, chars.Count),
                    randomChars[1][rand.Next(0, randomChars[1].Length)]);
            }
                
            if (opts.RequireDigit)
            {
                chars.Insert(rand.Next(0, chars.Count),

InterpolSystem.Web/Controllers/MissingPeopleController.cs
namespace InterpolSystem.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Models.MissingPeople;
    using Models.Shared;
    using Services;
    using Services.Blog;
    using Services.BountyAdmin;
    using System;

    using static WebConstants;

    public class MissingPeopleController : BasePeopleController
    {
        private readonly IArticleService articleService;
        private readonly IMissingPeopleService peopleService;

        public MissingPeopleController(
            IArticleService articleService,
            IMissingPeopleService peopleService,
            IBountyAdminService bountyAdminService)
            : base(bountyAdminService)
        {
            this.peopleService = peopleService;
            this.articleService = articleService;
        }

        public IActionResult Index(int page = 1)
            => View(new MissingPeoplePageListingModel
            {
                MissingPeople = this.peopleService.All(page, PageSize),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(this.peopleService.Total() / (double)PageSize),
                Countries = this.GetCountries(),
                Articles = articleService.LastSixArticles()
            });

        public IActionResult Details(int id)
        {
            var existingPerson = this.peopleService.IsPersonExisting(id);

            if (!existingPerson)
            {
                return BadRequest();
            }

            var person = this.peopleService.GetPerson(id);

            return View(person);
        }

        public IActionResult Search(SearchFormViewModel model, int page = 1)
            => View(new MissingPeoplePageListingModel
            {
                CurrentPage = page,
                MissingPeople = this.peopleService.SearchByComponents(
                    model.EnableCountrySearch,
                    model.SelectedCountryId ?? 0,
                    model.EnableGenderSearch,
                    model.SelectedGender,
                    model.SearchByFirstName,
                    model.SearchByLastName,
                    model.SearchByDistinguishMarks,
                    model.SearchByAge ?? 0,
                    page,
                    PageSize),
                SearchCriteriaTotalPages = this.peopleService.SearchPeopleCriteriaCounter,
                TotalPages = (int)Math.Ceiling(this.peopleService.SearchPeopleCriteriaCounter / (double)PageSize),
                Articles = articleService.LastSixArticles()
            });
    }
}

InterpolSystem.Web/Controllers/WantedPeopleController.cs
namespace InterpolSystem.Web.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using InterpolSystem.Services.Blog;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Shared;
    using Models.WantedPeople;
    using Services;
    using Services.BountyAdmin;
    using System;
    using System.Threading.Tasks;

    using static WebConstants;

    public class WantedPeopleController : BasePeopleController
    {
        private readonly IWantedPeopleService peopleService;
        private readonly UserManager<User> userManager;
        private readonly IArticleService articleService;

        public WantedPeopleController(
          IArticleService articleService,
          IWantedPeopleService peopleService,
          UserManager<User> userManager,
          IBountyAdminService bountyAdminService)
            : base(bountyAdminService)          
        {
            this.peopleService = peopleService;
            this.userManager = userManager;
            this.articleService = articleService;
        }

        public IActionResult Index(int page = 1)
            => View(new WantedPeoplePageListingModel
            {
                WantedPeople = this.peopleService.All(page, PageSize),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(this.peopleService.Total() / (double)PageSize),
                Countries = this.GetCountries(),
                Articles = articleService.LastSixArticles()
                
            });

        [Authorize(Roles = BountyHunterRole)]
        public IActionResult SubmitForm(int id)
            => View(new SubmitFormViewModel { Id = id });

        [HttpPost]
        [Authorize(Roles = BountyHunterRole)]
        public async Task<IActionResult> SubmitForm(SubmitFormViewModel model)
        {
            var currentUser = await this.userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                this.TempData.AddErrorMessage("Invalid user authentication.");
                return RedirectToAction(nameof(SubmitForm));
            }

            string ext = System.IO.Path.GetExtension(model.Image.FileName).ToLower();
            var lenght = model.Image.Length;
            if (!(ext == ".jpg" || ext == ".png" || ext == ".jpeg"))
            {
                ModelState.AddModelError(string.Empty, "File uploaded is not an image, please use .jpg/.jpeg/.png file");
            }
            if (lenght > 2000000)
            {
                ModelState.AddModelError(string.Empty, "File uploaded is too big maximum size is 2mb");
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            peopleService.SubmitForm(
                model.Id,
                currentUser.Id,
                model.PoliceDepartment,
                model.Subject,
                model.Message,
                currentUser.Email,
                model.Image);
            TempData.AddSuccessMessage("Form was sent to secretariat, you will be notified soon about the outcome");

            return RedirectToAction(nameof(Details), new { id = model.Id });
                
        }
        
        public IActionResult Details(int id)
        {
            var existingPerson = this.peopleService.IsPersonExisting(id);

            if (!existingPerson)
            {
                return BadRequest();
            }

            var person = this.peopleService.GetPerson(id);

            return View(person);
        }

        public IActionResult Search(SearchFormViewModel model, int page = 1)
           => View(new WantedPeoplePageListingModel
           {
               CurrentPage = page,
               WantedPeople = this.peopleService.SearchByComponents(
                   model.EnableCountrySearch,
                   model.SelectedCountryId ?? 0,
                   model.EnableGenderSearch,
                   model.SelectedGender,
                   model.SearchByFirstName,
                   model.SearchByLastName,
                   model.SearchByDistinguishMarks,
                   model.SearchByAge ?? 0,
                   page,
                   PageSize),
               SearchCriteriaTotalPages = this.peopleService.SearchPeopleCriteriaCounter,
               TotalPages = (int)Math.Ceiling(this.peopleService.SearchPeopleCriteriaCounter / (double)PageSize),
               Articles = articleService.LastSixArticles()
           });
    }
} 

InterpolSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UnderLaw Official Website</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

</head>
<body id="bootstrap-override">
    <nav class="navbar navbar-inverse navbar-fixed-top" id="main-nav-bar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/images/interpol-logo.png" class="main-logo" />
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">UnderLaw</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (this.User.IsInRole(WebConstants.AdministratorRole))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Manage Users
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" id="main-nav-bar">
                                <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">All Users</a></li>
                                <li><a asp-area="Admin" asp-controller="Users" asp-action="Create">Create User</a></li>
                                <li><a asp-area="Admin" asp-controller="Logger" asp-action="All">Saved Employees Operations</a></li>
                            </ul>
                        </li>
                    }
                    @if (this.User.IsInRole(WebConstants.AdministratorRole)
                      || this.User.IsInRole(WebConstants.WantedMissingPeopleRole))
                    {
                        <li class="dropdown">
                            <a id="managePeopleA" class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Manage  People
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" id="main-nav-bar">

                                <li><a asp-area="BountyAdmin" asp-controller="MissingPeople" asp-action="Create">Add Missing Person</a></li>
                                <li><a asp-area="BountyAdmin" asp-controller="WantedPeople" asp-action="Create">Add Wanted Person</a></li>
                                <li><a id="SubmitFormWantedA" asp-area="BountyAdmin" asp-controller="WantedPeople" asp-action="ListAllForms">Check wanted's forms</a></li>

                            </ul>
                        </li>

                    }
                    @if (this.User.IsInRole(WebConstants.BloggerRole))
                    {
                        <li><a asp-area="Blog" asp-controller="Articles" asp-action="Create">Publish News</a></li>
                    }
                    @if (this.User.IsInRole(WebConstants.BountyHunterRole))
                    {
                        <li><a asp-area="BountyHunter" asp-controller="BountyHunter" asp-action="GetSubmittedForms">My-Forms</a></li>
                    }
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Missing
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" id="main-nav-bar">
                            <li><a asp-controller="MissingPeople" asp-action="Index">Missing people</a></li>
                            <li><a asp-controller="WantedPeople" asp-action="Index">Wanted people</a></li>

                        </ul>
                    </li>
                    <li><a asp-area="Blog" asp-controller="Articles" asp-action="Index">News</a></li>

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempDataSuccessMessageKey]
            </div>
        }
        else if (TempData.ContainsKey(WebConstants.TempDataErrorMessageKey))
        {
            <div class="alert alert-danger">
                @TempData[WebConstants.TempDataErrorMessageKey]
            </div>
        }

        @RenderBody()
        <hr />
        <footer class="text-center col-md-12">
            <p>&copy; UnderLaw 2018. All rights reserved</p>
        </footer>
    </div>
    <div id="background"></div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    @{
        var result = ViewData[WebConstants.ValidForm];
    }
    <p class="result">@result</p>
</body>
</html>